networks:
  shopnet:
    external: true
    name: mini_shop_shopnet

volumes:
  grafana_data:
  prometheus_data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: mini_shop_prometheus
    mem_limit: 512m
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    networks:
      - shopnet

  grafana:
    image: grafana/grafana:latest
    container_name: mini_shop_grafana
    mem_limit: 512m
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - shopnet

  node-exporter:
    image: prom/node-exporter:latest
    container_name: mini_shop_node_exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - shopnet
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: mini_shop_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - shopnet

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: mini_shop_postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://shopuser:shoppass@mini_shop_db:5432/shop?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - shopnet

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: mini_shop_blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - shopnet

