global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["mini_shop_node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["mini_shop_cadvisor:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["mini_shop_postgres_exporter:9187"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://mini_shop_backend:5000/
          - http://mini_shop_db:5432/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mini_shop_blackbox:9115
