"""empty message

Revision ID: 42507e5664ae
Revises: 
Create Date: 2025-09-21 17:01:04.104940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42507e5664ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
